server.port=8081

spring.application.name=auth-service

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/hotel_auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=root
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:victus}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

app.jwt.secret=SG90ZWxSZXNlcnZhdGlvblN5c3RlbVNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbkFuZFZhbGlkYXRpb24yMDI0
app.jwt.expiration=86400000
app.admin.secret=HotelAdmin@2024

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html


# Logging
logging.level.root=INFO
logging.file.name=/logs/auth-service.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n